# Generated by Django 4.2.24 on 2025-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanDVFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mutation', models.DateField(blank=True, null=True)),
                ('nature_mutation', models.CharField(blank=True, max_length=100)),
                ('valeur_fonciere', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('no_voie', models.CharField(blank=True, max_length=10)),
                ('btq', models.CharField(blank=True, max_length=5, verbose_name='B/T/Q')),
                ('type_de_voie', models.CharField(blank=True, max_length=100)),
                ('code_voie', models.CharField(blank=True, max_length=10)),
                ('voie', models.CharField(blank=True, max_length=200)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('commune', models.CharField(blank=True, max_length=150)),
                ('code_departement', models.CharField(blank=True, max_length=3)),
                ('code_commune', models.CharField(blank=True, max_length=10)),
                ('prefixe_de_section', models.CharField(blank=True, max_length=10)),
                ('section', models.CharField(blank=True, max_length=10)),
                ('no_plan', models.CharField(blank=True, max_length=10)),
                ('no_volume', models.CharField(blank=True, max_length=10)),
                ('nombre_de_lots', models.PositiveIntegerField(blank=True, null=True)),
                ('code_type_local', models.CharField(blank=True, max_length=10)),
                ('type_local', models.CharField(blank=True, max_length=100)),
                ('identifiant_local', models.CharField(blank=True, max_length=50)),
                ('surface_reelle_bati', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_pieces_principales', models.PositiveIntegerField(blank=True, null=True)),
                ('nature_culture', models.CharField(blank=True, max_length=100)),
                ('nature_culture_speciale', models.CharField(blank=True, max_length=100)),
                ('surface_terrain', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clean DVF record',
                'verbose_name_plural': 'Clean DVF records',
                'ordering': ['-date_mutation', 'commune', 'code_postal'],
            },
        ),
    ]
