# Generated by Django 4.2.24 on 2025-09-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('parcel_count', models.PositiveIntegerField(default=0)),
                ('surface_area', models.FloatField(default=0.0)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insee_code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('centroid_lon', models.FloatField(blank=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, null=True)),
                ('parcel_count', models.PositiveIntegerField(default=0)),
                ('surface_area', models.FloatField(default=0.0)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='dvf_app.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
