# Generated by Django 4.2.24 on 2025-09-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dvf_app", "0002_department_municipality"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Municipality",
            new_name="Commune",
        ),
        migrations.RenameField(
            model_name="commune",
            old_name="insee_code",
            new_name="code_commune",
        ),
        migrations.AlterField(
            model_name="commune",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="communes",
                to="dvf_app.department",
            ),
        ),
    ]
