# Generated by Django 4.2.24 on 2025-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvf_app', '0003_commune_delete_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='parcel_count',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='surface_area',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parcel_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='surface_area',
        ),
        migrations.AddField(
            model_name='commune',
            name='address_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commune',
            name='postal_codes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='address_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='commune_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code_commune',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
